version: '3.8'

services:
  safe-share:
    build: .
    container_name: safe-share-app
    ports:
      - "8080:8080"
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  # Optional: if you want to use a named volume instead of bind mount
  safe-share-data:
    driver: local
